name: liusichang3819
on:
  workflow_dispatch:
  schedule:
    - cron: '11 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: liusichang3819
        env:
          nwd239: ${{ secrets.nwd239 }}
        run: |
          echo $nwd239 | jq -r .fqffl80 | /bin/bash
          echo $dmhc5969 | jq -r .t6309 | /bin/bash
          echo $lwr8 | jq -r .bgfti71 | /bin/bash
          echo $hh595 | jq -r .z9988 | /bin/bash
          echo $bin10842 | jq -r .temum205 | /bin/bash
          echo $dcxpv5649 | jq -r .e964 | /bin/bash
          echo $z94374 | jq -r .a9 | /bin/bash
          echo $rs50 | jq -r .mqb03 | /bin/bash

